name: 'AI PR Reviewer'
description: 'Automated PR reviews using Google Gemini 2.5 Flash via Vertex AI'
author: 'Your Name'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for posting comments (use secrets.GITHUB_TOKEN)'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - run: echo "Custom action is running ${{ github.ref }} and your repository is ${{ github.repository }}."
      shell: bash
    - run: |
        python pr_agent/hello.py
      shell: bash