name: 'AI PR Reviewer'
description: 'Automated PR reviews using Google Gemini 2.5 Flash via Vertex AI'
author: 'Your Name'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for posting comments (use secrets.GITHUB_TOKEN)'
    required: true
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'docker://europe-west2-docker.pkg.dev/iamreleased/docker-images/pr-review-agent:latest'